db/users.js, public/common.css, routes/login.js, routes/settings.js, routes/signup.js, server.js, views/account/profile/index.ejs, views/account/settings/index.ejs, views/account/settings/style.css, views/home/index.ejs, views/partials/navbar.ejs
This merge is a joint effort between front and backend code:
- The settings page displays the current user settings.
- The settings page allows these settings to be changed.
- The backend API receives the request and updates the settings in the database.
- The user's session and other frontend pages are updated with new values.
This PR also closes multiple smaller issues that I will link. Feel free to try modifying settings for yourself. There are a few minor changes that I will make a separate issue about, but for the most part this page is functional and does what it needs to.
=> Settings api

db/defaultSettings.json, db/users.js
Fixes consistency issues between default settings and those available to change on the settings page. Will close #54 .
=> Fixes errors associated with default settings.

views/account/generate_qr_code/index.ejs, views/account/generate_qr_code/main.js, views/account/profile/index.ejs, views/account/profile/main.js, views/account/profile/style.css
Makes the profile page look like Payton's mockup.
=> Pfp payton mockup

public/common.css, views/aboutus/index.ejs, views/account/profile/index.ejs, views/account/settings/index.ejs, views/account/signup/index.ejs, views/home/index.ejs, views/partials/footer.ejs, views/partials/navbar.ejs
Closes #61 
We don't have to merge this before class, but I had some free time today and wanted to tackle this since I implemented the footer originally.
It looks to be pretty good now, even with the stress testing i've put it under for both desktop and mobile versions.
I'd recommend running this on your side and making sure everything checks out.
=> Implements a fixed but content-aware footer

db/seed.js, db/userAccounts.js, db/users.js, routes/login.js, routes/profile.js, views/home/index.ejs
Closes #75.
The 4 functions added in this PR contain the basic CRUD operations required for easily creating, reading, updating, and deleting `user_account` entries from the database. Now, the endpoint API can be written using these functions in order for users on the front end to make real changes to the database on the back end.
=> Add accounts interface

views/account/profile/index.ejs, views/account/profile/main.js, views/account/profile/style.css, views/partials/header.ejs
1) Sets up the table so that it can eventually integrate with Payton's API calls to the db.
2) When you manage the accounts, a yellow alert pops up on top of the table to show that changes were made successfully.
=> Made profile page edits.

db/defaultSettings.json, public/common.js, routes/profile.js, views/aboutus/index.ejs, views/account/login/index.ejs, views/account/profile/index.ejs, views/account/profile/main.js, views/account/settings/index.ejs, views/account/settings/main.js, views/account/signup/index.ejs, views/home/index.ejs, views/home/main.js, views/partials/header.ejs
This is eventually going to be merged but the idea for this PR is that it's going to take the settings in the user's account and apply it throughout the website.
As of right now, the functionality works just for the profile page but the plan is to make a common file that returns the settings object so that it can be passed to every webpage.
You will probably run into an error but in order to see the working changes, comment out the common.js link the in the header partial.
=> Implement settings functionality

routes/displaycard.js, routes/notfound.js, server.js, views/account/profile/main.js, views/displaycard/index.ejs, views/displaycard/main.js, views/displaycard/style.css, views/notfound/index.ejs, views/notfound/style.css, views/partials/header.ejs
Makes a not found 404 page for nonexistent or expired business cards.
=> Not found page

views/aboutus/main.js, views/account/login/main.js, views/account/profile/main.js, views/account/settings/main.js, views/home/main.js, views/partials/header.ejs
This adds the font size and font family settings to each home page except for the ones where the user may not necessarily be logged in.
Closes #7 and Closes #107
=> Add font settings

views/partials/footer.ejs, views/partials/header.ejs, views/partials/navbar.ejs
Looks like the issue was due to too many bootstrap js links being imported. Not sure if it was because of me (Very would could've been tbh), but FYI is that importing multiple links for the bootstrap css / js libraries causes it to break since it's not sure which one to pick.
Closes #96
=> Fix dropdown

db/userAccounts.js, routes/profile.js, views/aboutus/main.js, views/account/profile/index.ejs, views/account/profile/main.js, views/partials/footer.ejs, views/partials/header.ejs, views/partials/navbar.ejs
Closes #93, closes #94, closes #98.
This PR refactors the existing profile page code in order to allow the user to click 'save changes' to apply updates to all modified accounts at once. This replaces the old functionality of just updating the modified field instantly.
There is client and server-side input validation. On the client side, buttons for adding a new account, canceling changes, and submitting changes all become disabled if the information is missing, reflecting similar behavior to most sites:
- The 'add account' button is disabled if there is an empty field in the add account portion of the form.
- The 'cancel changes' button is disabled if there have been no changes to the user's accounts.
- The 'submit changes' button is disabled if any of the accounts' textboxes are empty. …
=> Add save changes

db/cardEntry.js, db/schema.sql, db/seed.js
Closes #64
This adds the card_entries table as well as the Create, Get, Update and Delete associated with the table.
=> Creation of card_entries table and functions

routes/home.js, views/aboutus/main.js, views/account/profile/main.js, views/account/settings/main.js, views/displaycard/index.ejs, views/home/main.js
Closes #110, closes #127 
If you try running the app from `main` on your phone as of now, many of the asynchronous JavaScript features will fail to use the `await` keyword. They had to be replaced with the traditional `fetch`, `then`, `catch`, and `finally` chaining of promise resolution. Now, all JS functionality should be working on mobile browsers.
If you can try running this on your phones (for those of you whose phones are connecting to your computers), I would appreciate any feedback if some JS isn't working.
=> Fix mobile bug

README.md
Process for adding to this - Check out this branch, make changes, push.
The next you want to make changes, make sure you git pull before you push and you continue.
I re-opened this because I saw a formatting error. We're gonna be updating this again so it makes sense to have this PR up
=> READMe Update

views/home/main.js
For the Home page, I removed the value of the instagram handle to clean up interface. The user should not have to see their account handle/username again when it's already in the Profile page. This is just repeated information.
=> Removed value from homepage

db/defaultSettings.json, public/common.css, views/aboutus/index.ejs, views/aboutus/main.js, views/account/login/index.ejs, views/account/profile/index.ejs, views/account/profile/main.js, views/account/profile/style.css, views/account/settings/index.ejs, views/account/settings/main.js, views/account/signup/index.ejs, views/displaycard/index.ejs, views/home/index.ejs, views/home/main.js, views/home/style.css, views/notfound/index.ejs, views/partials/footer.ejs, views/partials/navbar.ejs
Closes #8, Closes #92, Closes #129 
This implements the light mode/dark mode setting by changing all of the text colors on the page to a scheme of white and gold or gold and navy blue.
There is an issue currently where when clicking on the link or refreshing, everything turns light gold. I'm looking into it.
=> Add theme settings

views/home/index.ejs, views/home/main.js
The difference is that .click() toggles the state where .checked = true changes the toggle to be on regardless of its state.
=> Made a tiny change that fixes a bug for the buttons on the home page (casual, professional, all).

public/common.css, views/aboutus/index.ejs, views/account/profile/index.ejs, views/account/profile/style.css, views/account/settings/index.ejs, views/home/index.ejs, views/home/main.js, views/partials/defaultSettings.ejs, views/partials/footer.ejs, views/partials/navbar.ejs, views/partials/setSettingsForm.ejs
Closes #62, Closes #91
I got this working on the settings page before #135 but I figured I'm gonna have to change this up a bit. I'll let you know when it's ready.
=> Implement contrast for settings page

views/partials/setSettingsForm.ejs
Closes #141 
Changes font family options to:
- Times New Roman
- Arial
- Verdana
- Trebuchet MS
=> Change font families

db/cardEntry.js, routes/displaycard.js, views/displaycard/index.ejs, views/displaycard/main.js, views/notfound/index.ejs, views/partials/defaultSettings.ejs
DON'T MERGE UNTIL AFTER CODING MILESTONE 2!
Closes #113. Introduces a small bug that will be fixed after #149 is merged.
Dynamic card content can now be seen for a specific Goon Card! Scanning the QR Code and navigating to the generated dynamic card now shows the first and last name of the owner, as well as the accounts that they selected to be shared for that card. 
NOTE: This PR introduces a small bug. If you try deleting an account that is associated with some generated Goon Card, the display card page may show 'undefined undefined' for the user's name. This bug is fixed in #149 by implementing the proper cascade code, meaning that deleting any `user_account` entry will delete all corresponding `card_entry` entries, so be mindful of this while testing.
=> Adds dynamic displaycard generation.

README.md, db/users.js, public/common.css, routes/settings.js, views/account/profile/index.ejs, views/account/profile/style.css, views/account/settings/index.ejs, views/home/index.ejs, views/partials/modal.ejs, views/partials/setSettingsForm.ejs
=> Support for user deletion

README.md
Since there are now 2 branches dedicated to just the ReadMe, they should be merged into one. Once this adds @thadakn1's changes, we can probably also merge the ReadMeRepo into the main branch.
=> Added more about accessibility in the readme

README.md
=> Adds VM access instructions to readme.
